build: false
environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.11"
    PYTHON_ARCH: "32"

    CONAN_UPLOAD: 1
    CONAN_REFERENCE: "jsoncpp/1.8.0"
    CONAN_USERNAME: "theirix"
    CONAN_CHANNEL: "ci"
    CONAN_TOTAL_PAGES: 4

    matrix:
        - CONAN_CURRENT_PAGE: 1
        - CONAN_CURRENT_PAGE: 2  
        - CONAN_CURRENT_PAGE: 3
        - CONAN_CURRENT_PAGE: 4
init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan_package_tools # It install conan too
  - conan user # It creates the conan data directory

test_script:
  - C:\Python27\python build.py
